[package]
name = "minigrep"
version = "0.1.0"
authors = ["Alexandre Roussel <alexandre.roussel@ssi.gouv.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
